# Generated by Django 5.1.7 on 2025-04-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0005_alter_bookinggroup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('payment_reference', models.CharField(max_length=255)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank', 'Bank Transfer'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('booking_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookinggroup')),
            ],
        ),
    ]
