# Generated by Django 5.1.7 on 2025-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_created_by_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_booked_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_policy',
            field=models.TextField(blank=True, help_text='Describe refund/cancellation policies'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_refundable',
            field=models.BooleanField(default=False, help_text='Are tickets refundable?'),
        ),
        migrations.AddField(
            model_name='event',
            name='refund_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for requesting a refund', null=True),
        ),
    ]
