# Generated by Django 5.1.7 on 2025-04-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_total_booked_tickets_bookinggroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinggroup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
